### ISSUE TITLE
Highlight broken on empty variable (`${}`)

### ISSUE THREAD

**Issue by korc** [Kipjr/vscode-language-ipxe#2]
**Describe the bug**
When using an empty variables `${}`, highlighting of the syntax after the variable breaks.

**To Reproduce**
1. Use a line with `${}` in middle of `.ipxe` file
2. Observe the following statements in the file not being properly highlighted anymore

**Expected behavior**
Recognize `${}` as normal variable

**Screenshots**
- broken (copy-paste from [iPXE documentation of the `read`](https://www.ipxe.org/cmd/read) command): 
![wrong](https://user-images.githubusercontent.com/125582/152288549-06cc9e13-c493-4555-939d-fabf3976d343.png)
- should be: 
![correct](https://user-images.githubusercontent.com/125582/152288564-5b9c4754-e70f-41c7-8e63-aa0992951d0e.png)

**Additional context**
Appending following to the `.repository.variable.patterns` in `syntaxes/ipxe.tmLanguage.json` seems to make it better
```json
{
    "name": "variable.empty",
    "match": "\\$\\{\\}"
},
```

**Comment by Kipjr** [comment]
@korc , it should be fixed with the most recent version
