### ISSUE TITLE
 Publish to Open VSX Registry #49 

### ISSUE THREAD

**Issue by adamcstephens** [Kipjr/vscode-language-ipxe#9]
**Is your feature request related to a problem? Please describe.**

As a user of VSCodium (or other open source builds of VS Code), I can't install this extension from a registry. 

**Describe the solution you'd like**

Please publish this extension to the Open VSX registry along with the Microsoft one. https://open-vsx.org/

**Describe alternatives you've considered**

Building or downloading the extension, and manually installing it on each machine.
Not using the extension.

**Additional context**

Thank you!

**Comment by Kipjr** [comment]
thanks I'm waiting for namespace claim request and I will publish the extension soon
